### PR TITLE
Make it possible to set spawnpoint during daytime

### PR DESCRIPTION
**Pull request by BigXplosion**
This PR makes it possible to set your spawnpoint during daytime. As this mods skips nighttime at a current percentage, it might be hard for everyone to set their spawn in a bed when you have a crowded server. This simply resolves that issue by allowing people to set their spawn point by simply right clicking the bed (only during daytime).

### CODE REVIEW

**Comment by Quetzi** [comment]
Thanks! I'll most likely want to add a config to enable turning this on and off, so I'll merge it when I get time to open my workspace, probably tomorrow.

**Comment by BigXplosion** [comment]
I could add the config option to the PR if you want me to?

**Comment by Quetzi** [comment]
You can if you like :) Either way I won't be able to get to it before tomorrow anyway.

**Comment by BigXplosion** [comment]
Done, I had nothing to do anyway :D

**Pull request merged**
